YP-1: Добавлена вёрстка экрана для quiz'а по фильмам. Добавлена логика работы приложения.
PowerSl1d3/MovieQuiz-ios pull request #2
Opened 2022-11-21 00:49 UTC by PowerSl1d3

2022-11-21 15:12 UTC, mmbabaev commented
Дизайн неверный - кнопки находятся над вопросом

2022-11-21 15:12 UTC, mmbabaev commented
У корневой StackView не хватает bottom constraint до safe area (проверить верстку на iPhone 14 plus).  
<img width="704" alt="Screen Shot 2022-11-21 at 16 48 27" src="https://user-images.githubusercontent.com/12600807/203071237-b3174e10-fa68-4c9e-b8c2-be67958027c6.png">


После этого проверьте верстку на iPhone 13 mini. Скорее всего нужно будет поправить верхний и нижний констрейнты лейбла вопроса на 0

<img width="495" alt="Screen Shot 2022-11-21 at 16 47 52" src="https://user-images.githubusercontent.com/12600807/203071104-244cba10-6e46-4f9c-b86d-9bb2a4aa83ed.png">

2022-11-21 15:13 UTC, mmbabaev requested changes

2022-11-21 15:13 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 15
неверное окргуление

2022-11-21 15:13 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Необязательно: если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-21 15:13 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
неверные цвета

2022-11-21 15:13 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 0
сбрасываете округление основной картинки

2022-11-22 06:20 UTC, PowerSl1d3 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 15
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44105323/203239608-d60d16c1-77cc-4575-adb4-312f122ea976.png">
поправил, теперь должно быть согласно макетам 20

2022-11-22 06:21 UTC, PowerSl1d3 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
ага, прокинул sender'а в метод и начал блокировать кнопку, которую уже нажали(другой момент, что всё ещё остаётся возможность тыкать на вторую кнопку в то время как первая нажата и наверное по хорошему полностью экран тогда нужно блокировать, но это другая история).

2022-11-22 06:22 UTC, PowerSl1d3 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
Теперь заиспользовал из библиотеки в Figm'е

2022-11-22 06:22 UTC, PowerSl1d3 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 0
Убрал это)

2022-11-22 06:28 UTC, PowerSl1d3 commented
Добавлю свой комментарий, а то на некоторые выше ответить нельзя было) Поправил отсупы у label'а на 10 от superview для него, поскольку согласно макетам между текстом и картинкой, а также кнопками, должно быть расстояние 20. Поэтому не совсем понял про расстояние 0.

2022-11-22 06:29 UTC, PowerSl1d3 commented
И ещё по поводу комментариев, не знаю просто как у вас флоу построен, но если что мы пользуемся следующим форматом: если кто-то начал комментирование, то он и резолвит обсуждение, если последующих вопросов нет, иначе обсуждение продолжается.

2022-11-22 18:17 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
можно вынести кнопки как iboutlet и блокировать обе

2022-11-22 18:21 UTC, mmbabaev commented
по обсуждению: принятие/перезачет работы можно считать за резолв/не резолв. Если на комментарии глаза, то он обязательный

2022-11-22 18:25 UTC, mmbabaev commented
Шрифт нижнего лейбла должен быть 23 bold. После этого проверьте iPhone 13 mini

2022-11-26 09:53 UTC, merged